---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build-pr
  image: rancher/dapper:v0.6.0
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - pull_request

- name: build-push-tag
  image: rancher/dapper:v0.6.0
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      include:
        - "refs/heads/main"
        - "refs/tags/v*"
    event:
    - push
    - tag

- name: github_binary_prerelease
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    title: "Pre-release ${DRONE_TAG}"
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
      include:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"
    event:
    - tag

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    title: "Release ${DRONE_TAG}"
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
      exclude:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"
    event:
    - tag

- name: docker-publish-prerelease
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/rancher-cleanup"
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
      include:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"
    event:
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/rancher-cleanup"
    tags:
      - "${DRONE_TAG}-amd64"
      - "latest-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
      exclude:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"
    event:
    - tag


volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---

kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest-prerelease
  image: plugins/manifest:1.2.3
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
    target: "rancher/rancher-cleanup:${DRONE_TAG}"
    template: "rancher/rancher-cleanup:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
      include:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"
    event:
    - tag

- name: manifest
  image: plugins/manifest:1.2.3
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
    target: "rancher/rancher-cleanup:${DRONE_TAG}"
    template: "rancher/rancher-cleanup:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
      exclude:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"
    event:
    - tag

- name: manifest-latest
  image: plugins/manifest:1.2.3
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
    target: "rancher/rancher-cleanup:latest"
    template: "rancher/rancher-cleanup:latest-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
      exclude:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"
    event:
    - tag

depends_on:
- amd64
