#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts
cp ./cleanup.sh ./verify.sh dist/artifacts/

sed -i -e 's/unreleased/'"$VERSION"'/' cleanup.sh
sed -i -e 's/unreleased/'"$VERSION"'/' verify.sh

IMAGE=${REPO}/rancher-cleanup:${TAG}
DOCKERFILE=package/Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
